 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- master

pr:
- master

resources:
  repositories:
  - repository: self
    ref: 'refs/heads/master'
  - repository: scripts
    type: github
    name: jdrush89/Card-Game
    ref: 'refs/heads/master'
    endpoint: JoshGithub
  - repository: sources
    type: github
    name: jdrush89/azure-devops-ui
    ref: 'refs/heads/master'
    endpoint: JoshGithub

jobs:
- job: multirepo
  pool: 'default'
  steps:
  - checkout: self
    clean: true
    path: yaml
  - checkout: scripts
    clean: true
    path: src
